#!/bin/bash

module load dislib/master
module load python/3.7.4
module unload COMPSs/2.10
module load COMPSs/.custom/TrunkGPS
export ComputingUnitsTree=16


# Define script constants
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# Create output directory
output_dir="${SCRIPT_DIR}/output"
mkdir -p "${output_dir}"

echo "Enqueueing Matmul's Recusive version with matrices of ${matrix_size}x${matrix_size} with blocks of ${final_block_size}x${final_block_size} doing a ${splits_per_step}x${splits_per_step} partition on each recursive step"

    # Create output directory
  output_dir="${SCRIPT_DIR}/output"
  mkdir -p "${output_dir}"

  # Run job
  enqueue_compss --qos=debug \
    --sc_cfg="mn.cfg" \
    \
    --num_nodes="16" \
    --exec_time="120" \
    --log_level=off \
    --constraints=highmem \
    --scheduler="es.bsc.compss.scheduler.orderstrict.fifo.FifoTS" \
    \
    --cpus_per_node=48 \
    --worker_in_master_cpus=48 \
    \
    --master_working_dir="${output_dir}/" \
    --worker_working_dir="${output_dir}/" \
    --base_log_dir="${output_dir}" \
    --log_dir="${output_dir}" \
    --pythonpath="${SCRIPT_DIR}/application" \
    \
    --jvm_workers_opts="-Dcompss.worker.removeWD=false" \
    \
    --agents \
    \
    --method_name="main" \
    --lang="python" \
    "main_forest_HIGGS_16_trees_nested_2"

